on: [push]

name: Tests

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: "pip3 install -r requirements.txt"
      - name: "Run pytest"
        run: "pytest"